kind: MLApp
metadata:
  name: gan-image-similarity
spec:
  package_manager: pip2
  packages:
    - names:
      - flask
      manager: pip2
  tasks:
  - name: prepare-data
    resources:
    - name: upload
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 1
      allowFail: true
      images:
        cpu: busybox
      command: rm -rf ut-zap50k-images*;wget http://vision.cs.utexas.edu/projects/finegrained/utzap50k/ut-zap50k-images.zip; unzip ut-zap50k-images.zip;mv ut-zap50k-images/* ./;rm -rf ut-zap50k-images*
      workdir: "$DATA_DIR"
      volumes:
      - name: data
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: tensorflow/tensorflow:1.2.0-gpu
        cpu: tensorflow/tensorflow:1.2.0
      command: python
      args: main.py --gan --logdir=$TRAINING_DIR/$BUILD_ID --batch_size=40 --file_pattern=$DATA_DIR/*/*/*/*.jpg --epochs=10
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 8Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
  - name: parallel
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: tensorflow/tensorflow:1.2.0-gpu
        cpu: tensorflow/tensorflow:1.2.0
      command: echo $TRAINING_DIR; echo $DATA_DIR; python
      args: parallel.py --role=worker --num_gpus=$GPU_COUNT --task $REPLICA_INDEX --ps_hosts $PS_NODES --worker_hosts $WORKER_NODES --logdir=$TRAINING_DIR/$BUILD_ID --batch_size=40 --file_pattern=$DATA_DIR/*/*/*/*.jpg --epochs=1
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 4Gi
      port: 2222
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
    - name: ps
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: tensorflow/tensorflow:1.2.0-gpu
        cpu: tensorflow/tensorflow:1.2.0
      command: echo $TRAINING_DIR; echo $DATA_DIR; python
      args: parallel.py --role=ps --task $REPLICA_INDEX --ps_hosts $PS_NODES --worker_hosts $WORKER_NODES
      workdir: "$SRC_DIR"
      port: 2222
      volumes:
      - name: src
  - name: similarity
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: tensorflow/tensorflow:1.2.0-gpu
        cpu: tensorflow/tensorflow:1.2.0
      command: python
      args: main.py --similarity --logdir=$TRAINING_DIR/2 --batch_size=40 --file_pattern=$DATA_DIR/*/*/*/*.jpg
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 8Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/mlboard-jupyter-gpu:latest"
      cpu: "kuberlab/mlboard-jupyter:latest"
    resources:
      requests:
        cpu: 100m
        memory: 125Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    volumes:
    - name: lib
      mountPath: /notebooks/lib
    - name: src
      mountPath: /notebooks/src
    - name: training
      mountPath: /notebooks/training
    - name: data
      mountPath: /notebooks/data
  - name: tensorboard
    displayName: Tensorboard
    command: "tensorboard"
    args: "--logdir=$TRAINING_DIR"
    images:
      cpu: "lsheiba/tensorflow-ls-devel"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    volumes:
    - name: training
  serving:
  - name: serving
    displayName: Serving
    images:
        gpu: tensorflow/tensorflow:1.2.0-gpu
        cpu: tensorflow/tensorflow:1.2.0
    workdir: "$SRC_DIR"
    command: python
    args: "serving2.py --logdir=$TRAINING_DIR/$BUILD_ID --batch_size=40 --file_pattern=$DATA_DIR/*/*/*/*.jpg"
    resources:
      accelerators:
        gpu: 1
        dedicated_gpu: true
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 8Gi
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    volumes:
    - name: training
    - name: data
    - name: src
    - name: lib
  volumes:
  - isLibDir: false
    isTrainLogDir: true
    mountPath: /training
    name: training
    clusterStorage: {{ .storage }}
    subPath: training
  - gitRepo:
      repository: https://github.com/kuberlab/zappos
    isLibDir: false
    isTrainLogDir: false
    mountPath: /src
    name: src
    subPath: "/zappos/src"
  - isLibDir: true
    isTrainLogDir: false
    mountPath: /workspace/lib
    name: lib
    clusterStorage: {{ .storage }}
    subPath: lib
  - isLibDir: false
    isTrainLogDir: false
    mountPath: /data
    name: data
    clusterStorage: {{ .storage }}
    subPath: /data/ut-zap50k-images
